### ISSUE TITLE
Bakla si benjamin

### ISSUE THREAD

**Issue by dennieljoshua** [oreoruhi/eSched.me-app#3]
Isa itong malaking issue

**Comment by dennieljoshua** [comment]
Hellom ang pogi ko talaga

>**Bold Ito**

**Comment by oreoruhi** [comment]
Naku, totoong issue nga yan.

**Comment by dennieljoshua** [comment]
Napakalaking issue, kelangan naten mag assign ng mas maramig tao, kung mag gigithub sana si dan xD
